# Logger Config
logging:
  config: classpath:logback.xml
  level:
    com.baomidou.mybatisplus.samples: debug
    org.springframework.cloud: info

spring:
  banner:
    location: classpath:banner-pro.txt
  application:
    name: itcc-mva
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: itccQCmanageDataSource
    url: jdbc:oracle:thin:@172.16.1.152:1521:aisinocc
    username: icc_union
    password: icc_union
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.itcc.mva.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: oracle
    #刷新mapper 调试神器
    refresh: true
    sql-parser-cache: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    #二级缓存使用 true 打开，false 关闭
    cache-enabled: false
    #生产需要禁止掉下面这个选项
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 52113
shedlock:
  defaults:
    lock-at-most-for: 1m

asrParams:
  recordsUrl: 172.16.12.229:9999
  isPathdir: false
  channelType: MONO
  audioFormat: auto
  property: chinese_8k_common
  fileExtention: .wav
  resultType: JSON
  wordsInfo: NONE
  enableCallback: false
  enableDigitnorm: false
  enableAddPunc: true
  enableDiarization: false
  enableEmotion: false
  enableSpeed: false
  parallel: 24

engineType:
  jttype: 0
  kdtype: 0
  altype: 0
  txtype: 0

jobtype:
  jtjob: 1
  kdjob: 1
  aljob: 1
  txjob: 0